export default [
  'Weight of moving object',
  'Weight of stationary object',
  'Length of moving object',
  'Length of stationary object',
  'Area of moving object',
  'Area of stationary object',
  'Volume of moving object',
  'Volume of stationary object',
  'Speed',
  'Force (Intensity)',
  'Stress or pressure',
  'Shape',
  "Stability of the object's composition",
  'Strength',
  'Duration of Action of Moving Object',
  'Duration of Action of Stationary Object',
  'Temperature',
  'Illumination intensity',
  'Use of Energy by moving object',
  'Use of Energy by stationary object',
  'Power',
  'Loss of energy',
  'Loss of substance',
  'Loss of information',
  'Loss of time',
  'Quantity of substance',
  'Reliability',
  'Measurement Accuracy',
  'Manufacturing Precision',
  'Object Affected Harmful factors',
  'Object-Generated Harmful Factors',
  'Ease of Manufacture',
  'Convenience of Use',
  'Ease of Repair',
  'Adaptability or Versatility',
  'Device Complexity',
  'Difficulty of Detecting and Measuring',
  'Extent of Automation',
  'Productivity',
];
