export default [
  'Segmentation',
  'Separation or extraction',
  'Local quality',
  'Asymmetry',
  'Merging or combining',
  'Universality',
  'Nesting dolls',
  'Counter-weight',
  'Preliminary counter-action',
  'Preliminary action',
  'Previously placed pillow',
  'Equipotential',
  'Other way around',
  'Spherical shapes',
  'Dynamism',
  'Partial or excessive action',
  'Moving to another dimension',
  'Mechanical vibration',
  'Periodic action',
  'Continuity of useful action',
  'Rushing through',
  'Blessing in disguise (harm to benefit)',
  'Feedback',
  'Intermediary',
  'Self-service',
  'Copying',
  'Cheap disposable',
  'Replace a mechanical system',
  'Pneumatics or hydraulics',
  'Flexible films or membranes',
  'Porous materials',
  'Optical changes',
  'Homogeneity',
  'Recycling (rejecting and regenerating)',
  'Physical or chemical properties',
  'Use phase changes',
  'Thermal expansion',
  'Strong oxidants',
  'Inert environment',
  'Composite materials',
];
